### GET TECNOLOGIES ###

GET http://localhost:3000/tecnologies?language=true


### ADD TECNOLOGY ###
POST http://localhost:3000/tecnologies
Content-Type: application/json

{
    "name": "javascript",
    "img": "https://teste.com"
}


### EDIT TECNOLOGY ###
DELETE  http://localhost:3000/tecnologies/1
